[package]
name = "legion"
version = "0.1.1"
description = "High performance entity component system (ECS) library"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
repository = "https://github.com/TomGillen/legion"
keywords = ["ecs", "game"]
categories = ["game-engines", "data-structures"]
readme = "readme.md"
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "TomGillen/legion", branch = "master" }

[features]
default = ["par-iter"]
par-iter = ["rayon"]

[dependencies]
slog = { version = "2.5", features = ["nested-values"] }
slog-stdlog = "4"
parking_lot = "0.9"
downcast-rs = "1.0"
itertools = "0.8"
rayon = { version = "1.2", optional = true }
derivative = "1"
smallvec = "0.6"
petgraph = "0.4"
hibitset = "0.6"

[dev-dependencies]
env_logger = "0.6"
slog-term = "2"
slog-async = "2"
criterion = "0.3"
cgmath = "0.17"

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "parallel_query"
harness = false

[[bench]]
name = "transform"
harness = false
